// Types for the Kumami Roadmap component.
// Drop at src/components/roadmap/types.ts

export interface RoadmapItem {
  /** Stable id; generated by createId() */
  id: string;
  /** What needs doing */
  text: string;
  /** ISO yyyy-mm-dd or null */
  deadline: string | null;
  /** Checked off */
  done: boolean;
}

export interface RoadmapCategory {
  id: string;
  name: string;
  items: RoadmapItem[];
}

export interface RoadmapState {
  version: number;
  updatedAt: string;
  categories: RoadmapCategory[];
}

export type BucketColor = 'red' | 'amber' | 'mint' | 'dim' | 'neutral';

export interface DeadlineBucket {
  label: string;
  color: BucketColor;
  /** Days from today; negative = overdue; null when no deadline set */
  diff: number | null;
  urgent: boolean;
}
