/**
 * Download coin logos for the top coins by market cap into public/coins/ and
 * write the symbol → file map used by coinLogo() (src/lib/coin-logos.generated.ts).
 * Logos are served from our own site, so the UI never depends on a third-party
 * image CDN at runtime. Coins not in the map fall back to the coloured letter.
 *
 *   npx tsx scripts/fetch-coin-logos.ts          # top 300 (default)
 *   npx tsx scripts/fetch-coin-logos.ts 500      # top N
 *
 * Re-run occasionally (e.g. monthly) to pick up new coins; it overwrites in place.
 * Source: CoinGecko /coins/markets (free tier, no key) — `image` per coin.
 * Symbol clashes: the coin with the higher market cap keeps the symbol.
 */
import fs from 'node:fs';
import path from 'node:path';

const TOP = Number(process.argv[2] ?? 300);
const OUT_DIR = 'public/coins';
const MAP_FILE = 'src/lib/coin-logos.generated.ts';
const CG = 'https://api.coingecko.com/api/v3';

type Market = { id: string; symbol: string; name: string; image: string; market_cap_rank: number | null };

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function getJson<T>(url: string): Promise<T> {
  for (let attempt = 1; ; attempt++) {
    const res = await fetch(url, { headers: { accept: 'application/json' } });
    if (res.ok) return res.json() as Promise<T>;
    if (res.status === 429 && attempt < 5) { await sleep(15_000 * attempt); continue; } // free-tier rate limit
    throw new Error(`${res.status} ${url}`);
  }
}

(async () => {
  const markets: Market[] = [];
  for (let page = 1; markets.length < TOP; page++) {
    // Fixed page size: CoinGecko pages are offsets of per_page, so it must not change between pages.
    const rows = await getJson<Market[]>(`${CG}/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page=${page}`);
    if (!rows.length) break;
    markets.push(...rows.slice(0, TOP - markets.length));
    await sleep(2_000);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const map: Record<string, string> = {};
  let failed = 0;
  for (const m of markets) {
    const sym = m.symbol.toUpperCase();
    if (!/^[A-Z0-9]{1,12}$/.test(sym) || map[sym] || !m.image) continue;
    // CoinGecko serves /large/ by default; /small/ (64px) is plenty for ≤32px badges at 2x.
    const url = m.image.replace('/large/', '/small/');
    const ext = (path.extname(new URL(url).pathname).toLowerCase() || '.png').replace('.jpeg', '.jpg');
    if (!['.png', '.jpg', '.webp', '.svg', '.gif'].includes(ext)) continue;
    const file = `${sym.toLowerCase()}${ext}`;
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(String(res.status));
      fs.writeFileSync(path.join(OUT_DIR, file), Buffer.from(await res.arrayBuffer()));
      map[sym] = file;
    } catch (e) {
      failed++;
      console.warn(`skip ${sym}: ${(e as Error).message}`);
    }
    await sleep(80);
  }

  const lines = Object.entries(map).sort(([a], [b]) => a.localeCompare(b)).map(([s, f]) => `  ${JSON.stringify(s)}: ${JSON.stringify(f)},`);
  fs.writeFileSync(MAP_FILE, `/**
 * GENERATED by scripts/fetch-coin-logos.ts — do not edit by hand.
 * Symbol → logo file in public/coins/ (top ${TOP} coins by market cap, ${new Date().toISOString().slice(0, 10)}).
 */
export const COIN_LOGO_FILES: Record<string, string> = {
${lines.join('\n')}
};
`);
  console.log(`Saved ${Object.keys(map).length} logos to ${OUT_DIR} (${failed} failed) and wrote ${MAP_FILE}`);
})().catch((e) => { console.error(e); process.exit(1); });
